### ISSUE TITLE
Create issue templates

### ISSUE THREAD

**Issue by mbos2** [mememania-org/mememania#10]
Create issue templates for next issue types, based on labels:

- [ ] - Enhancement  (New feature or request)
- [ ] - Bug (Something isn't working)
- [ ] - Documentation (Improvements or additions to documentation)
- [ ] - Pull request template

Ensure you read [ CONTRIBUTION](https://github.com/mememania-org/mememania/blob/main/CONTRIBUTING.md) and [CODE OF CONDUCT](https://github.com/mememania-org/mememania/blob/main/CODE_OF_CONDUCT.md) before submitting your PR.

**Comment by AmreshSinha** [comment]
Sure will create a PR :+1:
